### ISSUE TITLE
Make the json http body data not look awful

### ISSUE THREAD

**Issue by MclaughlinSteve** [MclaughlinSteve/automerge-kt#10]
Right now it's a string literal of the json object. It looks horrible. This should be generated instead. (i.e. I'd like to be able to write something like this for the body...)
```kt
    val json = JSONObject()
    json.put("head", pull.head.ref)
    json.put("base", pull.base.ref)
```

**Comment by tednology** [comment]
Consider using a `data class` here too. But that's also good 👍

**Comment by MclaughlinSteve** [comment]
Using data classes + jackson for this now.

Thanks for the help!
